import React from 'react';
import { ChevronLeft, Shield, FileText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const PageLayout = ({ title, children, icon: Icon }: any) => {
    const navigate = useNavigate();
    return (
        <div className="px-6 lg:px-10 pb-32 max-w-4xl mx-auto bg-transparent">
            <button onClick={() => navigate(-1)} className="mb-8 p-4 bg-white/5 border border-white/10 rounded-2xl text-white flex items-center gap-2 hover:bg-white/10 transition-all uppercase text-[10px] font-black tracking-widest">
                <ChevronLeft size={16} /> Back
            </button>
            <div className="bg-[var(--surface)] rounded-[3rem] border border-white/10 p-10 lg:p-16 shadow-2xl">
                <div className="flex items-center gap-5 mb-10">
                    <div className="w-16 h-16 bg-white/10 rounded-[1.5rem] flex items-center justify-center text-white">
                        <Icon size={32} />
                    </div>
                    <h2 className="text-3xl font-black text-white uppercase italic tracking-tighter">{title}</h2>
                </div>
                <div className="prose prose-invert max-w-none text-white/70 font-medium leading-relaxed space-y-8">
                    {children}
                </div>
            </div>
        </div>
    );
};

export const PrivacyPolicy = () => (
    <PageLayout title="Privacy Policy" icon={Shield}>
        <section>
            <h3 className="text-white text-xl font-black uppercase mb-4 tracking-tight">1. Data Collection</h3>
            <p>Edu-Flash collects minimal personal data required for operation. This includes your email address for account identification and any content you upload (images, text) for AI processing.</p>
        </section>
        <section>
            <h3 className="text-white text-xl font-black uppercase mb-4 tracking-tight">2. AI Processing</h3>
            <p>Uploaded documents are processed using Groq Cloud API. By using the app, you agree to have your data analyzed by third-party AI models (Llama 4, Vision) to generate study materials. Your data is not used to train these models.</p>
        </section>
        <section>
            <h3 className="text-white text-xl font-black uppercase mb-4 tracking-tight">3. Storage</h3>
            <p>Your generated flashcards and analyses are stored securely in Google Firebase. Local fallback data is stored in your browser's LocalStorage.</p>
        </section>
        <section>
            <h3 className="text-white text-xl font-black uppercase mb-4 tracking-tight">4. Payments</h3>
            <p>Payment processing is handled by Paddle. We do not store credit card information on our servers.</p>
        </section>
    </PageLayout>
);

export const TermsOfService = () => (
    <PageLayout title="Terms of Service" icon={FileText}>
        <section>
            <h3 className="text-white text-xl font-black uppercase mb-4 tracking-tight">1. Use of Service</h3>
            <p>Edu-Flash provides AI-powered study tools. You are responsible for the content you upload and ensuring it does not violate copyright laws or academic integrity policies.</p>
        </section>
        <section>
            <h3 className="text-white text-xl font-black uppercase mb-4 tracking-tight">2. AI Accuracy</h3>
            <p>Flashcards and summaries are generated by AI. While we strive for accuracy, the results may contain errors. Always verify critical information with your official study materials.</p>
        </section>
        <section>
            <h3 className="text-white text-xl font-black uppercase mb-4 tracking-tight">3. Quota & Subscriptions</h3>
            <p>Usage is limited by monthly quotas based on your plan (50/mo for Free, 500/mo for Pro). Quotas do not roll over to the next month.</p>
        </section>
        <section>
            <h3 className="text-white text-xl font-black uppercase mb-4 tracking-tight">4. Account Termination</h3>
            <p>We reserve the right to suspend or terminate accounts that abuse the AI service or violate these terms.</p>
        </section>
    </PageLayout>
);
